### ISSUE TITLE
安装报错  it is missing from your system. Install or enable PHP's wxwork_finance_sdk extension.

### ISSUE THREAD

**Issue by ecareyu** [mochat-cloud/mochat#1]
## 我用的环境

* PHP 版本：7.4.10
* MoChat 版本：master
* Swoole 版本：4.5.4

## 问题及现象

执行`composer install`
```
 Problem 1
    - Root composer.json requires mochat/wework-finance-sdk ^1.0 -> satisfiable by mochat/wework-finance-sdk[v1.0.0].
    - mochat/wework-finance-sdk v1.0.0 requires ext-wxwork_finance_sdk * -> it is missing from your system. Install or enable PHP's wxwork_finance_sdk extension.
```

**Comment by lnys** [comment]
问题是wxwork_finance_sdk这个扩展怎么装

**Comment by stone-ice** [comment]
1、这个扩展使用的是 https://github.com/pangdahua/php7-wxwork-finance-sdk。用来拉取聊天记录

2、因为该作者并没有写很详细的安装，只有具体的使用，所以我自己编写了一段shell，可以参考一下这个来编译 https://github.com/pangdahua/php7-wxwork-finance-sdk

3、当然，更推荐 https://mochatcloud.oss-cn-beijing.aliyuncs.com/deploy/CentOS-install.sh 这个shell，省去编译之苦

**Comment by maxincai** [comment]
> 1、这个扩展使用的是 https://github.com/pangdahua/php7-wxwork-finance-sdk 用来拉取聊天记录
> 
> 2、因为该作者并没有写很详细的安装，只有具体的使用，所以我自己编写了一段shell，可以参考一下这个来编译 https://github.com/pangdahua/php7-wxwork-finance-sdk
> 
> 3、当然，更推荐 https://mochatcloud.oss-cn-beijing.aliyuncs.com/deploy/CentOS-install.sh 这个shell，省去编译之苦

第二个的链接错了吧，应该是 https://github.com/oh-stone/wework-chatdata-sdk

**Comment by ecareyu** [comment]
@stone-ice 个人建议哈，别在安装脚本上花心思了， 维护一个脚本实在太费时间了，还不如把Dockerfile的源文件放出来，这样我们也好通过Dockerfile来看怎么部署环境。而且这个脚本目前只有centos，我们服务器事ubuntu。

**Comment by zhangyu19851112** [comment]
mac 下 wxwork_finance_sdk 这个扩展安装不了，这扩展能用composer 组件替代吗？

**Comment by maxincai** [comment]
> @stone-ice 个人建议哈，别在安装脚本上花心思了， 维护一个脚本实在太费时间了，还不如把Dockerfile的源文件放出来，这样我们也好通过Dockerfile来看怎么部署环境。而且这个脚本目前只有centos，我们服务器事ubuntu。
> 刚读了下你们测CentOS-innstall.sh这个脚本，好像只是一些常规的phpfpm环境，并没有融合php7wxwork-finance-sdk
> 
> 刚才试着编译了下那个扩展,返现会引发它文档里提到的那个bug
> `free(): invalid pointer`
> 我感觉，这个就比较麻烦了。

非常感谢你的建议，Dockerfile 源文件今天会放出，到时候会来这里回复。

CentOS 这个 Shell 脚本中的 PHP74 rpm 已经包含了 php7wxwork-finance-sdk 扩展

**Comment by maxincai** [comment]
> mac 下 wxwork_finance_sdk 这个扩展安装不了，这扩展能用composer 组件替代吗？

暂时没有

**Comment by igo9go** [comment]
为啥要用个额外的扩展啊

**Comment by stone-ice** [comment]
@zhangyu19851112 

> mac 下 wxwork_finance_sdk 这个扩展安装不了，这扩展能用composer 组件替代吗？

以后会推出composer包版本的，会以`FFI`形式引用微信官方的动态库(将来这个包会要求：PHP版本最低7.4)

**Comment by ianho7** [comment]
> @zhangyu19851112
> 
> > mac 下 wxwork_finance_sdk 这个扩展安装不了，这扩展能用composer 组件替代吗？
> 
> 以后会推出composer包版本的，会以`FFI`形式引用微信官方的动态库(将来这个包会要求：PHP版本最低7.4)

您好，请问这个是还没跟进吗？

**Comment by maxincai** [comment]
> > @zhangyu19851112
> > > mac 下 wxwork_finance_sdk 这个扩展安装不了，这扩展能用composer 组件替代吗？
> > 
> > 
> > 以后会推出composer包版本的，会以`FFI`形式引用微信官方的动态库(将来这个包会要求：PHP版本最低7.4)
> 
> 您好，请问这个是还没跟进吗？
已经支持FFI方式，需要你先开启FFI https://github.com/mochat-cloud/wework-finance-sdk
注意修改配置文件 wx_finance_sdk.php 'default'   => 'php-ffi',
