### ISSUE TITLE
建立个人二维码 选人  出现部分人员不在部门内部

### ISSUE THREAD

**Issue by ANfengXU** [mochat-cloud/mochat#10]
## 我用的环境

* PHP 版本：
* MoChat 版本：
* Swoole 版本：

## 问题及现象

部门结构 A 部门下 有 A1 和 A2 2个部门， 选择A 时出现5个人， 选择A1时出现 1个人， 选择A2时  没有人出现

**Comment by stone-ice** [comment]
感谢你的反馈。

我们正在切出修复完善的分支，来及时解决不同情况下的这些问题。

你的这个问题已经被我们这里收录等待测试。之后再反馈给你哈

**Comment by liuxiufang** [comment]
> ## 我用的环境
> * PHP 版本：
> * MoChat 版本：
> * Swoole 版本：
> 
> ## 问题及现象
> 部门结构 A 部门下 有 A1 和 A2 2个部门， 选择A 时出现5个人， 选择A1时出现 1个人， 选择A2时 没有人出现

您好，麻烦确认一下，是否成员属于A部门，但并非属于子部门A1和A2中，结果在选择A2时就不存在成员。

**Comment by stone-ice** [comment]
确实会有员工只属于父部门，而不属于任何子部门。我在demo的企业微信后台查了下，技术部是没有人的
