### ISSUE TITLE
无法登录 dashboard

### ISSUE THREAD

**Issue by ufosaga** [mochat-cloud/mochat#104]
## 我用的环境

* PHP 版本：7.4.3
* MoChat 版本：latest
* Swoole 版本：4.6.5
* Nodejs 版本：14.15.3

## 问题及现象
安装配置成功后，无法登录dashboard，提示未认证，没有token

* api, dashboard, sidebar 都部署完毕，域名和 nginx 反向代理都按照文档设置并且能够访问。
* php bin/hyperf.php mc:init 成功， 数据库各种表已经创建起来了
* mc_user 没有数据，执行了文档里写的两条sql：
```
INSERT INTO `mc_user` (`phone`,`password`,`status`,`isSuperAdmin`) VALUES ('13412347867','$2y$10$6PedNV6SVNQNpUMjZgauvewh7wfFjbSWbh2k9yGJ9dhAIBVcL4gKm',1,1);

INSERT INTO `mc_tenant` (`server_ips`) VALUES ('["182.92.11.11"]');
```

![1](https://user-images.githubusercontent.com/7089303/115333394-2b7dd800-a1cc-11eb-857e-5a40f9067997.png)
![2](https://user-images.githubusercontent.com/7089303/115333398-2d479b80-a1cc-11eb-9539-a70aa7f32097.png)
![3](https://user-images.githubusercontent.com/7089303/115333406-2f115f00-a1cc-11eb-8786-e8d547b92c60.png)

**Comment by maxincai** [comment]
1、php bin/hyperf.php mc:init 成功 应该会创建用户的，不用手动执行SQL创建用户。
2、SQL中的密码需要根据.env中的 SIMPLE_JWT_SECRET 来生成.
```
php -r "var_dump(password_hash(md5('具体密码' . ".env中的SIMPLE_JWT_SECRET"), PASSWORD_BCRYPT));"
```
