### ISSUE TITLE
消息存档的相关问题

### ISSUE THREAD

**Issue by wang3532429** [mochat-cloud/mochat#107]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：2.0
* Swoole 版本：4.6

## 问题及现象

1、消息存档在下载时间比较短的音频文件转mp3的时候会失败，返回为空，不知道是我的ffmpeg问题还是什么，我转成了wav就没啥问题

2、消息存档如果有语音通话的记录，在程序获取同步的时候会因为没有对语音通话类型作处理(并未传回roomid)导致异步
`[redis异步队列错误-message:] Undefined index: roomid`
应该视频通话也会导致这个错误吧，望下个版本进行完善下

**Comment by maxincai** [comment]
感谢反馈，已记录在优化计划中。

**Comment by maxincai** [comment]
最新版本已修复，请更新至最新代码
