### ISSUE TITLE
只有我自己的侧边栏编译后有两个Iod=app吗？

### ISSUE THREAD

**Issue by liuzhibo0725** [mochat-cloud/mochat#114]
只有我自己的侧边栏编译后有两个Iod=app吗？

**Comment by maxincai** [comment]
没明白是什么意思，请详细描述或提供截图。

**Comment by liuzhibo0725** [comment]
![1624003771099](https://user-images.githubusercontent.com/18436582/122529150-bace2d00-d04f-11eb-927d-71a09607c940.jpg)
就是我的侧边栏编译后有两个id=app

**Comment by liuzhibo0725** [comment]
可以告诉我怎么解决吗?????????
