### ISSUE TITLE
客户管理中，客户头像显示失败

### ISSUE THREAD

**Issue by ianho7** [mochat-cloud/mochat#115]
你好，我通过Docker玩了一下，发现客户管理里的头像显示不了，想请教一下是哪里没配置好？
![WechatIMG3](https://user-images.githubusercontent.com/26101033/122908843-2a615680-d387-11eb-9620-ca0da0edeef3.png)

**Comment by maxincai** [comment]
请用chrome等工具检查头像的路径是没有，还是路径错误。
* 如果没有头像地址，说明同步时上传失败，检查存储配置是否错误；
* 如果有头像地址，但是路径错误，请检查env中的后端域名是否配置正确；
