### ISSUE TITLE
老哥，你的密钥涉露了，速改！

### ISSUE THREAD

**Issue by jiangslee** [mochat-cloud/mochat#12]
# @stone-ice 老哥，项目很给力，不过你企业微信的密钥涉露了。。注意速改密钥

https://github.com/mochat-cloud/mochat/blob/76f3da2c85cd9cca720c9d26e96fbc00c5e22539/api-server/app/Model/Traits/CorpTrait.php#L50

**Comment by stone-ice** [comment]
@jiangslee 
感谢反馈，这是我们的疏忽，我们非常重视这个问题

我们已经及时在企业微信后台更新了secret。（另外，因为提问里的截图涉及到了公司员工的信息，这里做了去除，敬请谅解~）

原因：
1、我们的开发者在测试阶段，因不合理的测试手段，写死了密钥；
2、也因我的工作忙，在查代码方面做的不够好，遗漏了非常重要的这一点

反思：
规范是自觉的，流程是强制的。
我是倾向于从开发流程的角度上来规避这个问题，完善代码的上线流程。针对这次的重大问题，我们调整了一下计划
1、补充测试代码，利用hyperf的自动化测试组件来完善测试代码，以替换不合理的调试测试方式
2、编写安全检测脚本，放在测试阶段进行检测拦截
3、加强代码审查力度，最少两人以上的重复审查

@jiangslee 为了方便及时收集你的问题，我们非常希望你能在讨论群里添加我们的技术为好友，标注一下github的昵称，非常感谢

**Comment by jiangslee** [comment]
> @jiangslee
> 感谢反馈，这是我们的疏忽，我们非常重视这个问题
> 
> 我们已经及时在企业微信后台更新了secret。（另外，因为提问里的截图涉及到了公司员工的信息，这里做了去除，敬请谅解~）
> 
> 原因：
> 1、我们的开发者在测试阶段，因不合理的测试手段，写死了密钥；
> 2、也因我的工作忙，在查代码方面做的不够好，遗漏了非常重要的这一点
> 
> 反思：
> 规范是自觉的，流程是强制的。
> 我是倾向于从开发流程的角度上来规避这个问题，完善代码的上线流程。针对这次的重大问题，我们调整了一下计划
> 1、补充测试代码，利用hyperf的自动化测试组件来完善测试代码，以替换不合理的调试测试方式
> 2、编写安全检测脚本，放在测试阶段进行检测拦截
> 3、加强代码审查力度，最少两人以上的重复审查
> 
> @jiangslee 为了方便及时收集你的问题，我们非常希望你能在讨论群里添加我们的技术为好友，标注一下github的昵称，非常感谢

@stone-ice 已进开发者群6

**Comment by stone-ice** [comment]
@jiangslee 问题已合并到master，thanks
