### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by lltxwdk** [mochat-cloud/mochat#170]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：1.1
* Swoole 版本：4.7.1

## 问题及现象
服务部署好了，前端页面也弄好了，我在我本地电脑上任何浏览器访问是正常的，但是除了这台电脑以外，其他的电脑，包括手机，用浏览器访问就会报跨域错误

Access to XMLHttpRequest at 'http://api.yowub.com/dashboard/user/auth. from origin 'http://dashboard.yowub.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by maxincai** [comment]
请检查其他机器访问时 api 是否正确响应，如果未正确响应，api-server的跨域设置就会不效。
