### ISSUE TITLE
经常超时错误

### ISSUE THREAD

**Issue by lltxwdk** [mochat-cloud/mochat#176]
## 我用的环境

* PHP 版本：
* MoChat 版本：
* Swoole 版本：

## 问题及现象

您好，在测试的时候有个问题，就是会经常报超时错误，刷新页面也不行，但是过几分钟就正常了，想问下是配置的nginx有问题？还是后台不稳定造成的

**Comment by lltxwdk** [comment]
目前看nginx没有报超时，api-server的日志里好像是查询数据库等一系列操作后然后超时了，感觉像是服务有点不太稳定。

部分日志如下：
{"@timestamp":"2021-10-17T01:03:00.207471+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"Crontab task [monitorMessage] executed successfully at 2021-10-17 01:03:00.","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.208271+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.6] select `wx_agent_id` from `mc_work_agent` where `close` = '0' and `corp_id` = '1'","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.6}}
{"@timestamp":"2021-10-17T01:03:00.208545+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[1.63] select * from `mc_channel_code`","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":1.63}}
{"@timestamp":"2021-10-17T01:03:00.209214+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.41] select `last_id` from `mc_work_message_id` where `corp_id` = '1' and `type` = '1' and `mc_work_message_id`.`deleted_at` is null order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.41}}
{"@timestamp":"2021-10-17T01:03:00.209930+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.29] select `id` from `mc_work_message_1` order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.29}}
{"@timestamp":"2021-10-17T01:03:00.210410+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.34] select `wx_user_id` from `mc_work_employee` where `mc_work_employee`.`id` in ('1') and `mc_work_employee`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.34}}
{"@timestamp":"2021-10-17T01:03:00.210533+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[4.34] select `id`, `room_calendar_id`, `name`, `day`, `push_content` from `mc_room_calendar_push` where `day` = '2021-10-17 01:04' and `status` = '1' and `on_off` = '1' and `mc_room_calendar_push`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":4.34}}
{"@timestamp":"2021-10-17T01:03:00.210666+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.43] select `id`, `rooms`, `is_qrcode`, `is_link`, `is_miniprogram`, `is_card`, `is_keyword`, `keyword` from `mc_room_remind` where `corp_id` in ('1') and `status` = '1' and `mc_room_remind`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.43}}
{"@timestamp":"2021-10-17T01:03:00.211297+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.33] select `id`, `employee_secret`, `contact_secret`, `wx_corpid` from `mc_corp` where `mc_corp`.`id` = '1' limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.33}}
{"@timestamp":"2021-10-17T01:03:00.211289+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.29] select `id` from `mc_work_message_id` where `corp_id` = '1' and `type` = '1' and `mc_work_message_id`.`deleted_at` is null order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.29}}
{"@timestamp":"2021-10-17T01:03:00.211444+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"群日历任务2021-10-17 01:03:00","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.212994+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"Crontab task [RoomCalendar] executed successfully at 2021-10-17 01:03:00.","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.213470+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[1.77] select `column_key` as `column_key`, `column_name` as `column_name`, `data_type` as `data_type`, `column_comment` as `column_comment`, `extra` as `extra`, `column_type` as `column_type` from information_schema.columns where `table_schema` = 'mochat' and `table_name` = 'mc_work_message_id' order by ORDINAL_POSITION","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":1.77}}
{"@timestamp":"2021-10-17T01:03:00.219416+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[5.6] update `mc_work_message_id` set `last_id` = '0', `mc_work_message_id`.`updated_at` = '2021-10-17 01:03:00' where `id` = '1' and `mc_work_message_id`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":5.6}}
{"@timestamp":"2021-10-17T01:03:00.220009+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.28] select `wx_agent_id` from `mc_work_agent` where `close` = '0' and `corp_id` = '2'","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.28}}
{"@timestamp":"2021-10-17T01:03:00.220606+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.37] select `wx_agent_id` from `mc_work_agent` where `close` = '0' and `corp_id` = '3'","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.37}}
{"@timestamp":"2021-10-17T01:03:00.221484+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.31] select `last_id` from `mc_work_message_id` where `corp_id` = '3' and `type` = '1' and `mc_work_message_id`.`deleted_at` is null order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.31}}
{"@timestamp":"2021-10-17T01:03:00.222105+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.24] select `id` from `mc_work_message_3` order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.24}}
{"@timestamp":"2021-10-17T01:03:00.222781+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.42] select `id`, `rooms`, `is_qrcode`, `is_link`, `is_miniprogram`, `is_card`, `is_keyword`, `keyword` from `mc_room_remind` where `corp_id` in ('3') and `status` = '1' and `mc_room_remind`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.42}}
{"@timestamp":"2021-10-17T01:03:00.223544+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.35] select `id`, `from`, `room_id` from `mc_work_message_3` where `id` between '0' and '0' and `corp_id` = '3' and `from` like 'wm%' and `room_id` in ('7') and `msg_type` = '6' limit 5000","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.35}}
{"@timestamp":"2021-10-17T01:03:00.224185+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.34] select `id`, `from`, `room_id` from `mc_work_message_3` where `id` between '0' and '0' and `corp_id` = '3' and `from` like 'wm%' and `room_id` in ('7') and `msg_type` = '13' limit 5000","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.34}}
{"@timestamp":"2021-10-17T01:03:00.224813+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.38] select `id` from `mc_work_message_id` where `corp_id` = '3' and `type` = '1' and `mc_work_message_id`.`deleted_at` is null order by `id` desc limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.38}}
{"@timestamp":"2021-10-17T01:03:00.226329+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[1.19] select `column_key` as `column_key`, `column_name` as `column_name`, `data_type` as `data_type`, `column_comment` as `column_comment`, `extra` as `extra`, `column_type` as `column_type` from information_schema.columns where `table_schema` = 'mochat' and `table_name` = 'mc_work_message_id' order by ORDINAL_POSITION","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":1.19}}
{"@timestamp":"2021-10-17T01:03:00.230558+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[3.91] update `mc_work_message_id` set `last_id` = '0', `mc_work_message_id`.`updated_at` = '2021-10-17 01:03:00' where `id` = '2' and `mc_work_message_id`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":3.91}}
{"@timestamp":"2021-10-17T01:03:00.230647+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"群消息提醒执行完成2021-10-17 01:03:00","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.230702+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"客户群提醒2021-10-17 01:03:00","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.230830+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"Crontab task [RoomRemind] executed successfully at 2021-10-17 01:03:00.","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}
{"@timestamp":"2021-10-17T01:03:00.592487+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.58] select `wx_user_id` from `mc_work_employee` where `mc_work_employee`.`id` in ('3') and `mc_work_employee`.`deleted_at` is null","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.58}}
{"@timestamp":"2021-10-17T01:03:00.593440+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"[0.41] select `id`, `employee_secret`, `contact_secret`, `wx_corpid` from `mc_corp` where `mc_corp`.`id` = '2' limit 1","type":"mochat","channel":"sql","level":"INFO","monolog_level":200,"context":{"execTime":0.41}}
{"@timestamp":"2021-10-17T01:03:00.991792+08:00","@version":1,"host":"iZwz9hqwizo4t61yqt2hubZ","message":"Crontab task [channelCode] executed successfully at 2021-10-17 01:03:00.","type":"mochat","channel":"sys","level":"INFO","monolog_level":200}

**Comment by maxincai** [comment]
长时间无反馈，关闭处理。
