### ISSUE TITLE
是退出操作后，重新登陆，企业列表数据消失

### ISSUE THREAD

**Issue by gaoyunch** [mochat-cloud/mochat#18]
## 我用的环境

* PHP 版本：7.4.14
* MoChat 版本：master
* Swoole 版本：4.6.1

## 问题及现象

RT

https://user-images.githubusercontent.com/30514120/105626166-22999680-5e69-11eb-9edd-f611a3577d32.mov

**Comment by stone-ice** [comment]
@gaoyunch 
一、暂时处理方案：用该超管的手机号，在企业微信后台的员工管理，新添加一个员工

二、我们的计划：

这个原产品设计思路是，这个超管必须是已添加企业的员工。因为即使是超管，如果不属于任何企业，那么官网微信接口将无法有效调用

但是为了更好的完善这个系统，这块的业务企业关联，我们计划分离出来，脱离企业而操作相应数据。之后会有相应commit合并，请之后查看

**Comment by gaoyunch** [comment]
这个手机号原本就是这个企业的员工

**Comment by gaoyunch** [comment]
@stone-ice 不过这个手机号关联了多个企业，是这个原因吗？

**Comment by stone-ice** [comment]
@gaoyunch 可以拉取1.x分支更新一下代码。另外，因为此次设计的变更（当然，为了更好的接入CRM系统），波及到了租户。所以需要更新一下企业表，如下
```SQL
ALTER TABLE `mochat`.`mc_corp` 
ADD COLUMN `tenant_id` int(11) NULL DEFAULT 0 COMMENT '租户ID' AFTER `encoding_aes_key`;
```

另外，`api-server/storage/install/mochat.sql`也已同步更新。

**Comment by peiyan-w** [comment]
@stone-ice  还需要兼容老数据，需要执行  update mc_corp set tenant_id = 1;

**Comment by gaoyunch** [comment]
我是初始化项目重新测试

https://user-images.githubusercontent.com/30514120/105844528-5107a500-6014-11eb-8ab1-1d871a79e427.mov
重新登录还是会有422选择企业的错误，后续操作都正常 @peiyan-w @stone-ice
