### ISSUE TITLE
报错500

### ISSUE THREAD

**Issue by hangjw** [mochat-cloud/mochat#186]
## 我用的环境

* PHP 版本：7.2
* MoChat 版本：
* Swoole 版本：4.5

## 问题及现象
General error: 1525 Incorrect TIMESTAMP value: ''2021-11-17'' (SQL: select count(`id`) as aggregate from `mc_shop_code_record` where `corp_id` = 1 and `type` = 1 and `created_at` > '2021-11-17' and `mc_shop_code_record`.`deleted_at` is null)[1082] in /opt/www/vendor/hyperf/database/src/Connection.php","type":"mochat","channel":"sys","level":"ERROR","monolog_level":400}

![image](https://user-images.githubusercontent.com/18435675/142156707-e3cea786-dbf8-4fb0-8d9f-560edb033aba.png)
![image](https://user-images.githubusercontent.com/18435675/142156717-6bf51e6e-283b-4d89-a754-899f966e6641.png)

**Comment by maxincai** [comment]
已收到反馈，处理中。
