### ISSUE TITLE
消息存档不好用!

### ISSUE THREAD

**Issue by likewangjianxin** [mochat-cloud/mochat#190]
## 我用的环境

docker版本

## 问题及现象

我添加完了企业，并配置好企业的信息，使用消息存档功能没有任何消息，我查看源代码后发现MessageSyncDataTask的注释上写着TODO 本功能暂未启用。消息存档这个功能现在是咱不可用么？

**Comment by maxincai** [comment]
这个文件暂时注释了，有其他的任务在跑，功能是可以用的。
