### ISSUE TITLE
operation  前端  执行  yarn  install   出错

### ISSUE THREAD

**Issue by andy236726493** [mochat-cloud/mochat#192]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：v1.1.5
* Swoole 版本：4.5

## 问题及现象

operation  前端  执行  yarn  install   出错

gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.node-gyp/16.15.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/www/wwwroot/mochat/operation/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/root/.node-gyp/16.15.0/include/node -I/root/.node-gyp/16.15.0/src -I/root/.node-gyp/16.15.0/deps/openssl/config -I/root/.node-gyp/16.15.0/deps/openssl/openssl/include -I/root/.node-gyp/16.15.0/deps/uv/include -I/root/.node-gyp/16.15.0/deps/zlib -I/root/.node-gyp/16.15.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++14 -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
g++: error: unrecognized command line option ‘-std=gnu++14’
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
make: Leaving directory `/www/wwwroot/mochat/operation/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/www/wwwroot/mochat/operation/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 3.10.0-1160.53.1.el7.x86_64
gyp ERR! command "/www/server/nvm/versions/node/v16.15.0/bin/node" "/www/wwwroot/mochat/operation/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /www/wwwroot/mochat/operation/node_modules/node-sass
gyp ERR! node -v v16.15.0

**Comment by xiongamo** [comment]
nodejs版本太高，需要高版本的gcc，用低版本的nodejs即可
