### ISSUE TITLE
微信废弃了通讯录同步功能，是否有计划更新新的同步方案

### ISSUE THREAD

**Issue by boyfoo** [mochat-cloud/mochat#197]
## 问题及现象

微信废弃了同步通讯录使用到的接口，是否有计划更新新的方案？

https://developer.work.weixin.qq.com/document/path/96079

**Comment by hxer520** [comment]
作者现在主要心思在商业化上,估计开源的....

**Comment by jythons** [comment]
你好，通讯录、部门数据同步问题已修复，感谢使用
