### ISSUE TITLE
后台服务异常.hard错误

### ISSUE THREAD

**Issue by maxgod** [mochat-cloud/mochat#61]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：最新
* Swoole 版本：4.5

## 问题及现象

部署完请求接口报   后台服务异常.hard

**Comment by stone-ice** [comment]
这个要看具体的日志，估计是.env里什么东西没配置，具体的看 runtime下的error日志，那里有详细的错误。

如果部署环境为dev，并且用superivisor配置了stdout.log，那么就去这里面找日志

**Comment by maxincai** [comment]
长时间未回复，关闭处理。
