### ISSUE TITLE
首次没有同步外部联系人和外部群

### ISSUE THREAD

**Issue by yunlongliang** [mochat-cloud/mochat#63]
首次搭建成功之后，客户标签正常同步到页面，客户列表没有数据，数据库中也没有数据。

**Comment by maxincai** [comment]
点击客户列表的右下角同步按纽，看看日志有无报错。

**Comment by yunlongliang** [comment]
点击客户同步后，页面提示，"后台同步中，请稍后"，有两个请求，1，put http://api.mochat.heihe.co/workContact/synContact
响应 {"code":200,"msg":"","data":[]}。 GET http://api.mochat.heihe.co/workContact/index?fieldId=0&fieldType=0&fieldValue=&gender=3&addWay=全部&roomId=&groupNum=3&employeeId=&page=1&perPage=10 响应：{"code":200,"msg":"","data":[]}

**Comment by maxincai** [comment]
查看runtime/logs中的日志

**Comment by maxincai** [comment]
长时间未回复，关闭处理。
