### ISSUE TITLE
聊天侧边栏加载错误

### ISSUE THREAD

**Issue by happywrl** [mochat-cloud/mochat#65]
## 我用的环境

* PHP 版本：7.4.15
* MoChat 版本：1.x
* Swoole 版本：4.6

## 问题及现象

聊天侧边栏加载错误

前端提示 ：{"code":100012,"msg":"资源未找到","data":[]}

后端错误代码截图如下：
![屏幕快照 2021-02-25 15 47 32](https://user-images.githubusercontent.com/79630593/109125998-b7a0ef80-7787-11eb-825a-f011a1308dc3.png)

**Comment by maxincai** [comment]
应该是后端接口地址配置错误

**Comment by baitongda** [comment]
我也遇到这个问题了
![image](https://user-images.githubusercontent.com/7539571/110405502-a6c37880-80bb-11eb-9b72-e6aa0411201a.png)
后端这个配置页面也配好了。

**Comment by baitongda** [comment]
域名一定要ssl吗

**Comment by maxincai** [comment]
> 域名一定要ssl吗

不需要
