### ISSUE TITLE
php.ini 需要给多少内存？一直提示内存不足

### ISSUE THREAD

**Issue by maxincai** [mochat-cloud/mochat#7]
## 我用的环境

* PHP 版本：
* MoChat 版本：
* Swoole 版本：

## 问题及现象

php.ini 需要给多少内存？一直提示内存不足

**Comment by maxincai** [comment]
php.ini 内存调大一点，至少1024M/1G

参数的设置，可以参考hyperf官方docker的配置,https://github.com/hyperf/hyperf-docker/blob/master/7.4/alpine/swoole/Dockerfile

**Comment by txlong** [comment]
yarn install
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "25.2.1"
error Found incompatible module.
