### ISSUE TITLE
多人渠道码创建失败

### ISSUE THREAD

**Issue by baitongda** [mochat-cloud/mochat#70]
## 我用的环境

* PHP 版本：7.4
* MoChat 版本：1.X
* Swoole 版本：4.6

## 问题及现象

![image](https://user-images.githubusercontent.com/7539571/110415139-4c7ee380-80cc-11eb-8f80-a8bd0f38944e.png)

**Comment by maxincai** [comment]
请提供 runtime/logs 下的完整报错日志

**Comment by maxincai** [comment]
请检查对应的多人是否开通对外联系人权限，参考 第 5 和 6 步

https://mochat.wiki/wework/how-to-authorize.html
