### ISSUE TITLE
请问添加企业微信时一直超时可能是什么原因呀？

### ISSUE THREAD

**Issue by jiangxiaotang** [mochat-cloud/mochat#75]
## 我用的环境

* PHP 版本：7.4.14
* MoChat 版本：Github checkout 最新版本
* Swoole 版本：4.6.4

## 问题及现象

添加企业微信，总是超时，后台Debug信息也没看到什么错误。但就是不能添加成功。请问是什么原因呀？

**Comment by maxincai** [comment]
请提供 runtime/logs 下的完整报错日志

**Comment by maxincai** [comment]
已在其他沟通渠道解决
