### ISSUE TITLE
mc:init 执行不成功时如何处理

### ISSUE THREAD

**Issue by maxincai** [mochat-cloud/mochat#8]
## 我用的环境

* PHP 版本：
* MoChat 版本：
* Swoole 版本：

## 问题及现象

mc:init 执行不成功时如何处理

**Comment by maxincai** [comment]
可以手动初始化：
```
解决方案：

1、cp .env.example .env
2、将 .env 中的 DB REDIS OSS DOMAIN 配置完成
3、将数据库文件导入初始化 api-server/storage/install/mochat.sql
4、初始租户和账号信息，请注意修改下面的手机号和服务器IP，以下用户密码是 123456

INSERT INTO `mc_user` (`phone`,`password`,`status`,`isSuperAdmin`) VALUES ('13412347867','$2y$10$6PedNV6SVNQNpUMjZgauvewh7wfFjbSWbh2k9yGJ9dhAIBVcL4gKm',1,1);

INSERT INTO `mc_tenant` (`server_ips`) VALUES ('["182.92.11.11"]');

**Comment by xiaobopang** [comment]
手动初始化后，登录提示：“ 未认证,没有token ”

**Comment by xiaobopang** [comment]
> 可以手动初始化：
> 
> ```
> 解决方案：
> 
> 1、cp .env.example .env
> 2、将 .env 中的 DB REDIS OSS DOMAIN 配置完成
> 3、将数据库文件导入初始化 api-server/storage/install/mochat.sql
> 4、初始租户和账号信息，请注意修改下面的手机号和服务器IP，以下用户密码是 123456
> 
> INSERT INTO `mc_user` (`phone`,`password`,`status`,`isSuperAdmin`) VALUES ('13412347867','$2y$10$6PedNV6SVNQNpUMjZgauvewh7wfFjbSWbh2k9yGJ9dhAIBVcL4gKm',1,1);
> 
> INSERT INTO `mc_tenant` (`server_ips`) VALUES ('["182.92.11.11"]');
> ```

手动初始化后，登录提示：“ 未认证,没有token ”
