### ISSUE TITLE
外部群聊机器人

### ISSUE THREAD

**Issue by Zhu-Zi** [mochat-cloud/mochat#89]
## 问题1:
企业微信外部群聊机器人有相关第三方应用或者有开发计划吗？
## 问题2:
群管理支持对发广告自动踢人吗？
## 问题3:
dotnet core 版本的 mochat 在不在开发计划内呀？

**Comment by maxincai** [comment]
问题1:
企业微信外部群聊机器人有相关第三方应用或者有开发计划吗？
答：目前已经有类似的产品，不在 mochat 中，可以加我微信了解。

问题2:
群管理支持对发广告自动踢人吗？
答：其他产品支持

问题3:
dotnet core 版本的 mochat 在不在开发计划内呀？
答：目前暂不在开发计划中，如果有兴趣，可以贡献。
