### ISSUE TITLE
聊天侧边栏客户画像提示422错误

### ISSUE THREAD

**Issue by haodaa** [mochat-cloud/mochat#90]
## 我用的环境

* PHP 版本：7.3.1
* MoChat 版本：2.0
* Swoole 版本：4.6

![微信图片_20210408093747](https://user-images.githubusercontent.com/17821798/113955344-2163ed00-984e-11eb-9c58-fb4f494130a4.jpg)

后台已同步通讯录，登录企业微信的账号也已在后台创建

**Comment by maxincai** [comment]
该问题已在最新版本中修复，请更新至最新版。
